import { useEffect, useState } from 'react'
import { Plus, Search, ShieldCheck, X } from 'lucide-react'
import { api, type Facility, type Municipality, type PatientSummary, type PendingRequest } from './api'

export default function AdminPatients() {
  const [patients, setPatients] = useState<PatientSummary[]>([])
  const [facilities, setFacilities] = useState<Facility[]>([])
  const [municipalities, setMunicipalities] = useState<Municipality[]>([])
  const [open, setOpen] = useState(false)
  const [error, setError] = useState('')
  const [created, setCreated] = useState('')
  const [assigning, setAssigning] = useState('')
  const [reviewing, setReviewing] = useState('')
  const [requests, setRequests] = useState<PendingRequest[]>([])
  const [selected, setSelected] = useState<PatientSummary | null>(null)
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('all')
  const [notice, setNotice] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<PendingRequest | null>(null)
  const load = () => api.patients().then(setPatients)
  const loadRequests = () => api.pendingRequests().then(setRequests)
  useEffect(() => { Promise.all([load(), loadRequests(), api.facilities().then(setFacilities), api.municipalities().then(setMunicipalities)]).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); setSelected(null); setDeleteTarget(null) } }; document.addEventListener('keydown', closeOnEscape); return () => document.removeEventListener('keydown', closeOnEscape) }, [])
  const review = async (referenceCode: string, decision: 'accept' | 'reject') => { setError(''); setNotice(''); setReviewing(`${referenceCode}:${decision}`); try { await api.reviewRequest(referenceCode, decision); if (decision === 'accept') { const delivery = await api.dispatchWebhooks(); setNotice(delivery.sent ? `Request ${referenceCode} accepted and instructions sent.` : `Request ${referenceCode} accepted. Delivery remains queued; check Make connection.`) } await loadRequests() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to review request') } finally { setReviewing('') } }
  const removeRequest = async (referenceCode: string) => { setError(''); setNotice(''); setReviewing(`${referenceCode}:delete`); try { await api.deleteRequest(referenceCode); setDeleteTarget(null); setNotice(`Request ${referenceCode} permanently deleted.`); await loadRequests() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete request') } finally { setReviewing('') } }
  const assign = async (patientCode: string, facilityCode: string) => { if (!facilityCode) return; setAssigning(patientCode); try { await api.assignPatient(patientCode, facilityCode); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to assign care center') } finally { setAssigning('') } }
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError(''); setCreated(''); const form = new FormData(event.currentTarget)
    try { const result = await api.createPatient({ email: String(form.get('email') || '') || undefined, phone: String(form.get('phone') || '') || undefined, preferred_channel: String(form.get('preferred_channel')) as 'email' | 'sms', email_consent: form.get('email_consent') === 'on', sms_consent: form.get('sms_consent') === 'on', municipality: String(form.get('municipality')), age_group: String(form.get('age_group')), diagnosis_date: String(form.get('diagnosis_date') || '') || undefined, treatment_status: String(form.get('treatment_status')), referral_notes: String(form.get('referral_notes') || '') }); setCreated(result.patient_code); event.currentTarget.reset(); setOpen(false); void load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create patient') }
  }
  const locations = Object.entries(patients.reduce<Record<string, number>>((counts, patient) => { counts[patient.municipality] = (counts[patient.municipality] || 0) + 1; return counts }, {})).sort((a, b) => b[1] - a[1]).slice(0, 8)
  const maxLocationCount = locations[0]?.[1] || 1
  const pendingRequests = requests.filter(request => request.status === 'pending')
  const awaitingRequests = requests.filter(request => request.status === 'ticket_sent')
  const linkedPatients = patients.filter(patient => patient.treatment_status === 'on_treatment' || patient.care_status === 'assigned').length
  const filteredPatients = patients.filter(patient => (statusFilter === 'all' || patient.care_status === statusFilter) && [patient.patient_code, patient.municipality, patient.age_group, patient.treatment_status].some(value => value.toLowerCase().includes(query.trim().toLowerCase())))
  const maskContact = (request: PendingRequest) => { const value = request.contact_value || request.email || request.phone || ''; if (!value) return 'Unavailable'; return value.includes('@') ? value.replace(/^(.{2}).*(@.*)$/, '$1••••$2') : `${value.slice(0, 3)}••••${value.slice(-2)}` }
  return <section className="patient-page">
    <header><div><p className="eyebrow">Confidential care navigation</p><h1>Patient Monitoring</h1><p>Use pseudonymous codes to coordinate care. Contact and clinical details remain separated.</p></div><button onClick={() => setOpen(true)}><Plus size={17} />Add patient</button></header>
    {created && <div className="patient-success" role="status"><ShieldCheck size={18} />Patient created. Secure code: <strong>{created}</strong></div>}{notice && <div className="patient-success" role="status"><ShieldCheck size={18} />{notice}</div>}{error && <p className="login-error" role="alert">{error}</p>}
    <div className="patient-overview"><div className="patient-stat"><small>Total patients</small><strong>{patients.length}</strong><span>Pseudonymous records</span></div><div className="patient-stat"><small>Pending review</small><strong>{pendingRequests.length}</strong><span>Admin decision needed</span></div><div className="patient-stat"><small>Awaiting confirmation</small><strong>{awaitingRequests.length}</strong><span>Instructions issued</span></div><div className="patient-stat"><small>Linked to care</small><strong>{linkedPatients}</strong><span>Assigned or on treatment</span></div></div>
    <div className="patient-dashboard"><div className="registration-chart"><div className="panel-heading"><div><small>Registration origin</small><h2>Top municipalities</h2></div></div>{locations.length ? locations.map(([name, count]) => <div className="chart-row" key={name}><span title={name}>{name}</span><i aria-hidden="true"><b style={{ width: `${(count / maxLocationCount) * 100}%` }} /></i><strong>{count}</strong></div>) : <p className="panel-empty">No registration data.</p>}</div><div className="request-summary"><small>Intake workflow</small><h2>{requests.length} active requests</h2><p><strong>{pendingRequests.length}</strong> need review. <strong>{awaitingRequests.length}</strong> await patient confirmation.</p></div></div>
    {requests.length > 0 && <div className="request-queue"><div className="panel-heading"><div><small>Public intake</small><h2>Care requests</h2></div><span>Contacts masked by default</span></div><div className="table-wrap"><table><caption className="sr-only">Public care requests</caption><thead><tr><th>Reference</th><th>Municipality</th><th>Status</th><th>Channel</th><th>Contact</th><th>Received</th><th>Action</th></tr></thead><tbody>{requests.map(request => { const accepting = reviewing === `${request.reference_code}:accept`; return <tr key={request.reference_code}><td><strong>{request.reference_code}</strong></td><td>{request.municipality}</td><td><span className={`status-chip ${request.status}`}>{request.status === 'pending' ? 'Pending review' : 'Awaiting confirmation'}</span></td><td>{request.preferred_channel}</td><td>{maskContact(request)}</td><td>{new Date(request.created_at).toLocaleString()}</td><td className="request-actions">{request.status === 'pending' ? <><button disabled={Boolean(reviewing)} onClick={() => void review(request.reference_code, 'accept')}>{accepting ? 'Accepting…' : 'Accept'}</button><button className="danger-action" disabled={Boolean(reviewing)} onClick={() => setDeleteTarget(request)}>Delete</button></> : <span className="muted-action">No action needed</span>}</td></tr> })}</tbody></table></div></div>}
    <div className="patient-list-heading"><div><small>Patient records</small><h2>Care registry</h2></div><div className="patient-filters"><label><span className="sr-only">Search patients</span><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search code or municipality" /></label><select aria-label="Filter by care status" value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="all">All care statuses</option>{[...new Set(patients.map(patient => patient.care_status))].map(status => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></div></div>
    <div className="table-wrap patient-table"><table><caption className="sr-only">Patient care registry</caption><thead><tr><th>Patient code</th><th>Municipality</th><th>Age group</th><th>Care status</th><th>Treatment</th><th>Contact</th><th>Care center</th><th>Added</th></tr></thead><tbody>{filteredPatients.map(p => <tr key={p.patient_code} className="patient-row"><td><button className="code-link" onClick={() => setSelected(p)}><strong>{p.patient_code}</strong></button></td><td>{p.municipality}</td><td>{p.age_group.replaceAll('_', ' ')}</td><td><span className="status-chip">{p.care_status.replaceAll('_', ' ')}</span></td><td>{p.treatment_status.replaceAll('_', ' ')}</td><td>{p.preferred_channel}</td><td><select aria-label={`Assign ${p.patient_code} to care center`} disabled={assigning === p.patient_code || !facilities.length} defaultValue="" onChange={e => void assign(p.patient_code, e.target.value)}><option value="">Assign center</option>{facilities.map(f => <option key={f.facility_code} value={f.facility_code}>{f.name} · {f.municipality}</option>)}</select></td><td>{new Date(p.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>
    {!loading && !filteredPatients.length && !error && <p className="panel-empty">{patients.length ? 'No patients match these filters.' : 'No patient records.'}</p>}
    {selected && <div className="intake-backdrop" onClick={() => setSelected(null)}><div className="patient-detail" onClick={event => event.stopPropagation()}><button className="analytics-close" onClick={() => setSelected(null)} aria-label="Close"><X size={20} /></button><p className="eyebrow">Patient record</p><h2>{selected.patient_code}</h2><dl><dt>Municipality</dt><dd>{selected.municipality}</dd><dt>Age group</dt><dd>{selected.age_group.replaceAll('_', ' ')}</dd><dt>Care status</dt><dd>{selected.care_status.replaceAll('_', ' ')}</dd><dt>Treatment linkage</dt><dd>{selected.treatment_status.replaceAll('_', ' ')}</dd><dt>Preferred contact</dt><dd>{selected.preferred_channel}</dd><dt>Added</dt><dd>{new Date(selected.created_at).toLocaleString()}</dd></dl><p className="intake-note">Contact details and clinical notes stay restricted. This view shows only data returned by the patient summary endpoint.</p></div></div>}
    {deleteTarget && <div className="intake-backdrop" role="presentation"><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-request-title"><p className="eyebrow">Permanent action</p><h2 id="delete-request-title">Delete {deleteTarget.reference_code}?</h2><p>This permanently removes request before review. This cannot be undone.</p><div><button onClick={() => setDeleteTarget(null)}>Cancel</button><button className="danger-action" disabled={Boolean(reviewing)} onClick={() => void removeRequest(deleteTarget.reference_code)}>{reviewing ? 'Deleting…' : 'Delete permanently'}</button></div></div></div>}
    {open && <div className="intake-backdrop"><form className="intake-modal" onSubmit={submit}><button type="button" className="analytics-close" onClick={() => setOpen(false)} aria-label="Close">×</button><p className="eyebrow">Minimum necessary data</p><h2>Add patient</h2><div className="intake-grid"><label>Municipality<select name="municipality" required><option value="">Select municipality</option>{municipalities.map(m => <option key={m.PSGC} value={m.LOCATION}>{m.LOCATION} · {m.PROVINCE}</option>)}</select></label><label>Age group<select name="age_group" required><option value="">Select</option><option value="under_18">Under 18</option><option value="18_24">18–24</option><option value="25_34">25–34</option><option value="35_44">35–44</option><option value="45_54">45–54</option><option value="55_plus">55+</option><option value="not_disclosed">Not disclosed</option></select></label><label>Preferred contact<select name="preferred_channel" required><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Email<input name="email" type="email" autoComplete="off" /></label><label>Phone<input name="phone" type="tel" autoComplete="off" /></label><label>Diagnosis date, optional<input name="diagnosis_date" type="date" /></label><label>Treatment linkage<select name="treatment_status" required><option value="not_linked">Not linked</option><option value="referred">Referred</option><option value="on_treatment">On treatment</option><option value="not_disclosed">Not disclosed</option></select></label><label className="intake-wide">Referral notes<textarea name="referral_notes" maxLength={1000} /></label></div><label className="consent"><input name="email_consent" type="checkbox" />Patient explicitly consents to email contact</label><label className="consent"><input name="sms_consent" type="checkbox" />Patient explicitly consents to SMS contact</label><p className="intake-note">Do not enter names, exact addresses, HIV details, or unrelated medical notes.</p><button className="home-primary" type="submit">Create secure patient code</button></form></div>}
  </section>
}
