import { Activity, ArrowRight, Database, GitBranch, Map, ShieldCheck, Sparkles } from 'lucide-react'
import './model-page.css'

const inputs = ['Monthly reported case scenarios', 'Population and growth projections', 'Population density', 'Active testing-center counts', 'Municipality boundaries and adjacency', 'Care-cascade assumptions']
const outputs = ['Predicted cases', 'Transmission pressure index', 'Hotspot classes and clusters', 'Regional summaries and alerts', 'Testing-center need scores', 'Uncertainty-aware planning scenarios']

export default function ModelPage() {
  return <section className="page model-page">
    <div className="model-hero"><div><p className="eyebrow"><Sparkles size={14} /> ARCHIVE MODEL LAB · REGION XII</p><h1>From signals<br /><em>to insight.</em></h1><p className="lead">A transparent mathematical system for exploring how population, care access, time, and neighboring municipalities interact in HIV prevention planning.</p></div><div className="model-orbit" aria-label="Three dimensional model layers"><i className="orbit-core">MLR<br />LSTM</i><span>DATA</span><span>TIME</span><span>SPACE</span><b>MODEL<br />FIELD</b></div></div>
    <div className="model-stats"><span><strong>49</strong> municipalities and cities</span><span><strong>2025—2050</strong> forecast horizon</span><span><strong>MONTHLY</strong> time resolution</span><span><strong>AGGREGATE</strong> privacy boundary</span></div>
    <section className="model-section"><p className="eyebrow">01 · The evidence layer</p><h2>What data enters ARCHIVE?</h2><p className="section-intro">The system works with municipality-level records and modeled inputs. It does not require names, individual diagnosis, or personal contact details for public analytics.</p><div className="data-columns"><div><h3>Inputs</h3>{inputs.map((item, i) => <div className="data-row" key={item}><span>0{i + 1}</span>{item}</div>)}</div><div><h3>Data boundary</h3><div className="boundary-card"><ShieldCheck /><strong>Public analytics stay aggregated.</strong><p>Maps and rankings describe places and periods. Care-navigation contact details live in a separate protected operational workflow.</p></div></div></div></section>
    <section className="model-section"><p className="eyebrow">02 · The model stack</p><h2>Three lenses. One planning view.</h2><div className="model-grid"><article><Database /><small>DATA ENGINE</small><h3>Normalize</h3><p>Monthly municipality records are filtered to Region XII, aligned by period, and checked for model eligibility.</p><div className="equation">xᵢ,ₜ = {'{cases, population, density, centers}'}</div></article><article><Activity /><small>FORECAST ENGINE</small><h3>Learn time</h3><p>MLR provides interpretable relationships. LSTM reads sequences and learns temporal memory. A municipality embedding represents local differences.</p><div className="equation">ŷᵢ,ₜ = f<sub>MLR</sub>(xᵢ,ₜ) + f<sub>LSTM</sub>(xᵢ,ₜ₋ₙ:ₜ)</div></article><article><Map /><small>SPATIAL ENGINE</small><h3>Connect places</h3><p>Boundary adjacency and distance-based fallback weights estimate neighboring influence. Spatial statistics identify concentrations and clusters.</p><div className="equation">Pᵢ,ₜ = αRᵢ,ₜ + βΣⱼwᵢⱼRⱼ,ₜ</div></article><article><GitBranch /><small>DECISION LAYER</small><h3>Translate signals</h3><p>Forecasts become pressure scores, alerts, regional summaries, and testing-access candidates—not clinical conclusions.</p><div className="equation">score = scale(signal, neighbors, access)</div></article></div></section>
    <section className="model-section"><p className="eyebrow">03 · What happens each month?</p><div className="timeline"><div><b>01</b><strong>Observe</strong><span>Load monthly place-level inputs.</span></div><ArrowRight /><div><b>02</b><strong>Forecast</strong><span>Estimate future patterns through 2050.</span></div><ArrowRight /><div><b>03</b><strong>Diffuse</strong><span>Blend local and neighboring pressure.</span></div><ArrowRight /><div><b>04</b><strong>Explain</strong><span>Publish scores, maps, alerts, and caveats.</span></div></div></section>
    <section className="model-section outputs-section"><div><p className="eyebrow">04 · The output layer</p><h2>What the system produces</h2><p className="section-intro">Outputs support comparison and prioritization. They do not identify a person, prove transmission between places, or replace medical advice.</p></div><div className="output-list">{outputs.map((item, i) => <div key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}</div>)}</div></section>
    <section className="model-method"><h2>Model honesty is part of model quality.</h2><p>Case values are constrained development simulations, not official municipality-time surveillance. Transmission pressure is a deterministic population scenario, not R₀ or individual risk. Center recommendations are planning candidates, not approved sites. Uncertainty grows with forecast distance.</p></section>
  </section>
}
